feat(tracing): added hook to integrate with pino logger
MapColonies/telemetry pull request #17
Opened 2021-04-20 13:00 UTC by CptSchnitz

2021-04-20 19:31 UTC, syncush requested changes

2021-04-20 19:31 UTC, syncush commented on src/tracing/loggerHook.ts
> +  }
build args once and then use `method.apply` once

2021-04-20 19:31 UTC, syncush commented on tests/tracing/loggerHook.spec.ts
> +    provider.register({ contextManager: new AsyncHooksContextManager() });
lets register once

2021-04-21 05:42 UTC, CptSchnitz commented on src/tracing/loggerHook.ts
> +export function logMethod(this: Logger, args: Args, method: LogFn, level: number): void {
done

2021-04-21 05:42 UTC, CptSchnitz commented on src/tracing/loggerHook.ts
> +  }
done

2021-04-21 05:42 UTC, CptSchnitz commented on tests/tracing/loggerHook.spec.ts
> +    provider.register({ contextManager: new AsyncHooksContextManager() });
done

2021-04-21 05:51 UTC, syncush approved these changes

2021-04-21 06:51 UTC, merged