feat(metrics): added collectMetricsExpressMiddleware and deprecated defaultNodeMetrics
MapColonies/telemetry pull request #54
Opened 2023-07-07 11:02 UTC by syncush

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✔                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2023-08-03 08:50 UTC, CptSchnitz requested changes

2023-08-03 08:50 UTC, CptSchnitz commented on CHANGELOG.md
> +
?

2023-08-03 08:50 UTC, CptSchnitz commented on package.json
> +  "version": "5.1.13",
?

2023-08-03 08:50 UTC, CptSchnitz commented on src/metrics/middleware/metrics.ts
> +};
move to a common util area

2023-08-03 08:50 UTC, CptSchnitz commented on src/metrics/middleware/metrics.ts
> +  const defaultOpts: Opts = {
maybe upgrade typescript version and try the satisfy keyword

2023-08-03 08:50 UTC, CptSchnitz commented on src/metrics/middleware/metrics.ts
> +  if (meregedOptions.collectNodeMetrics) {
merged

2023-08-27 10:25 UTC, syncush commented on src/metrics/middleware/metrics.ts
> +  if (meregedOptions.collectNodeMetrics) {
done

2023-08-27 10:27 UTC, syncush commented on src/metrics/middleware/metrics.ts
> +};
done

2023-08-27 10:28 UTC, syncush commented on package.json
> +  "version": "5.1.13",
done

2023-08-27 10:33 UTC, syncush commented on src/metrics/middleware/metrics.ts
> +  const defaultOpts: Opts = {
done

2023-08-27 10:55 UTC, merged