feat(tracing): add utils for using spans
MapColonies/telemetry pull request #58
Opened 2023-12-27 10:12 UTC by rannyeli

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

Further  information:

Added several utilities to ease the usage of tracing spans when executing specific logics that require tracing.

2023-12-28 15:24 UTC, syncush requested changes

2023-12-28 15:24 UTC, syncush commented on src/tracing/utils/tracing.ts
> +};
```suggestion
  return new Promise((resolve, reject) => {
    return tracer.startActiveSpan(spanName, (span) => {
      fn()
        .then((result) => {
          handleSpanOnSuccess(span);
          return resolve(result);
        })
        .catch((error) => {
          handleSpanOnError(span, error);
          return reject(error);
        });
    });
  });
};
```

2023-12-28 15:24 UTC, syncush commented on src/tracing/utils/tracing.ts
> +};
what if the function has arguemnts, they need to be passed too, am I wrong?

2023-12-31 13:10 UTC, rannyeli commented on src/tracing/utils/tracing.ts
> +};
this util here is gonna take a callback for the desired function call. so the args will be passed inside the callback.
it will look something like this: `callWithSpan(() => someMethod(arg1, arg2), ...)` .
And I have just committed also decorators for a simple usage of these utils.

2023-12-31 13:54 UTC, rannyeli commented on src/tracing/utils/tracing.ts
> +  }
I think it's a best practice at any case, to be able to opt-out from using our extra logic of adding a span and avoid side effects of our code or OTel's code

2024-01-01 11:42 UTC, CptSchnitz requested changes

2024-01-01 11:42 UTC, CptSchnitz commented on src/metrics/middleware/metrics.ts
> +      });
why was this changed? its out of scope.

2024-01-01 11:42 UTC, CptSchnitz commented on src/metrics/middleware/metrics.ts
> +      });
why was this changed? its out of scope.

2024-01-01 11:42 UTC, CptSchnitz commented on src/tracing/tracing.ts
>            '@opentelemetry/instrumentation-pino': { enabled: false },
```suggestion
          ['@opentelemetry/instrumentation-pino']: { enabled: false },
```
With this you dont need the eslint-ignore.

2024-01-01 12:31 UTC, CptSchnitz approved these changes

2024-01-01 12:34 UTC, rannyeli commented on src/metrics/middleware/metrics.ts
> +      });
updating eslint raised an error about this code. so I changed it a bit to resolve it. the logic should remain the same.

2024-01-01 12:34 UTC, rannyeli commented on src/metrics/middleware/metrics.ts
> +      });
updating eslint raised an error about this code. so I changed it a bit to resolve it. the logic should remain the same.

2024-01-02 11:18 UTC, syncush approved these changes

2024-01-02 11:19 UTC, merged