feat: wip first naive json db semantic-conv
MapColonies/telemetry pull request #63
Opened 2024-03-28 15:22 UTC by ronenkapelian

MapColonies implementaion for semantic convention of project attributes

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

* first imlementation of static db (json) based.

* Raster domain oriented

2024-04-08 08:43 UTC, CptSchnitz requested changes
GJ!
Please go over the code files and improve the spacing and grouping of related code parts.

2024-04-08 08:43 UTC, CptSchnitz commented on schemas/attribute.schema.json
Add descriptions to the various fields

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +const DEPRECATION_JS_DOCSTRING = `* @deprecated and should use newer attributes\n`;
```suggestion
const DEPRECATION_JS_DOCSTRING = `* @deprecated Change to new attribute if this one was replaced \n`;
```

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +console.log(`Detect ${dbFiles.length} domains db files: ${dbFiles}`);
Why did you disable the lint?

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +function generateConstantTsFile(
```suggestion
function generateTsFile(
```

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +  deprecated: boolean | undefined
should this also be `isDomainDeprecated`?

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/validate-semantic-conventions.mts
> +const SCHEMA_DIR = 'schemas';
no need for two variables, merge into one.

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +const SEMANTIC_ATTRIBUTES_DIR = 'src/semanticConventions';
use `path.join` or `path.sep` instead of hardcoded `/`

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +const PACKAGE_INDEX_DIR = 'src/semanticConventions/index.ts';
use `path.join` or `path.sep` instead of hardcoded `/`

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/build-semantic-conventions.mts
> +const dbFiles = readdirSync(SEMANTIC_ATTRIBUTES_DIR).filter((file) => file.endsWith('.json'));
```suggestion
const dbFiles = readdirSync(SEMANTIC_ATTRIBUTES_DIR).filter((file) => path.extname(file) === '.json');
```

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/validate-semantic-conventions.mts
> +const SEMANTIC_ATTRIBUTES_DIR = 'src/semanticConventions';
use `path.join` or `path.sep` instead of hardcoded `/`

2024-04-08 08:43 UTC, CptSchnitz commented on scripts/validate-semantic-conventions.mts
> +const dbFiles = readdirSync(SEMANTIC_ATTRIBUTES_DIR).filter((file) => file.endsWith('.json'));
use same way as the other comment about checking extname

2024-04-08 08:43 UTC, CptSchnitz commented on src/semanticConventions/README.md
> +
As we talked, this is not needed, only short section on when and how to generate types

2024-04-08 08:43 UTC, CptSchnitz commented on src/semanticConventions/README.md
> +* This package goal is to provide flexible and easy to use auto-generated naming utils, such as attributes, names and constants.
```suggestion
* This package goal is to provide flexible and easy to provide semantic conventions to be used for telemetry purposes across all of MapColonies services.
```

2024-04-08 08:43 UTC, CptSchnitz commented on src/semanticConventions/README.md
> +* Support Javascript & Typescript compatibility
```suggestion
* Support Javascript & Typescript.
```

2024-04-08 08:43 UTC, CptSchnitz commented on src/semanticConventions/README.md
> +* Each Domain define its own domain.json and pass it to validation & auto-generate Typescripts types and code.
```suggestion
* Each Domain define its own json file that describes the semantic conventions of the domain. The package handles the validation of the file and the generation of files for use in code.
```

2024-04-08 08:43 UTC, CptSchnitz commented on src/semanticConventions/README.md
> +
```suggestion
[!IMPORTANT]
If OpenTelemetry already defined a value as part of their semantic conventions, use that and do not define a new one
```

2024-04-08 10:09 UTC, ronenkapelian commented on package.json
> +    "prebuild": "npm run clean && npm run validate && npm run generateTypes && npm run generateAttributes",
removed.

2024-04-08 10:10 UTC, ronenkapelian commented on package.json
> +    "generateTypes": "json2ts schemas/attribute.schema.json > scripts/autogen.mts",
done

2024-04-08 10:12 UTC, ronenkapelian commented on scripts/build-semantic-conventions.mts
> +const SEMANTIC_ATTRIBUTES_DIR = 'src/semanticConventions';
done

2024-04-08 10:18 UTC, ronenkapelian commented on scripts/build-semantic-conventions.mts
> +console.log(`Detect ${dbFiles.length} domains db files: ${dbFiles}`);
refactored and removed the disable -> used Array.join(',')

2024-04-08 10:19 UTC, ronenkapelian commented on scripts/build-semantic-conventions.mts
> +const PACKAGE_INDEX_DIR = 'src/semanticConventions/index.ts';
changed.

2024-04-08 10:21 UTC, ronenkapelian commented on scripts/build-semantic-conventions.mts
> +  deprecated: boolean | undefined
changed

2024-04-08 10:24 UTC, ronenkapelian commented on scripts/validate-semantic-conventions.mts
> +const SEMANTIC_ATTRIBUTES_DIR = 'src/semanticConventions';
done

2024-04-08 10:24 UTC, ronenkapelian commented on scripts/validate-semantic-conventions.mts
> +const dbFiles = readdirSync(SEMANTIC_ATTRIBUTES_DIR).filter((file) => file.endsWith('.json'));
done

2024-04-08 10:27 UTC, ronenkapelian commented on scripts/validate-semantic-conventions.mts
> +const SCHEMA_DIR = 'schemas';
done -> 'SCHEMA_DIR'

2024-04-09 17:01 UTC, shimoncohen commented
If this a WIP, then please don't add the `feat!` commitlint type.
@CptSchnitz What do you think?

2024-04-09 17:03 UTC, CptSchnitz commented
I added this as the ts config changes breaks existing code.
and the output is not wip

2024-04-09 17:04 UTC, CptSchnitz commented
> If this a WIP, then please don't add the `feat!` commitlint type.
> @CptSchnitz What do you think?

I added this as the ts config changes breaks existing code.
and the output is not wip.

2024-04-09 17:14 UTC, shimoncohen commented
> > If this a WIP, then please don't add the `feat!` commitlint type.
> > @CptSchnitz What do you think?
> 
> I added this as the ts config changes breaks existing code. and the output is not wip.

Ok, NP.

2024-04-09 18:11 UTC, shimoncohen requested changes

2024-04-11 05:50 UTC, CptSchnitz approved these changes

2024-04-14 07:47 UTC, merged