feat: add job manager conventions
MapColonies/telemetry pull request #68
Opened 2024-06-20 08:53 UTC by razbroc

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2024-06-23 08:35 UTC, asafMasa requested changes

2024-06-23 08:35 UTC, asafMasa commented on src/semanticConventions/infra.json
> +          "status": {
do you think jobStatus is better?

2024-06-23 08:35 UTC, asafMasa commented on src/semanticConventions/infra.json
> +            "description": "Status of job as stored on db (COMPLETED/ IN-PROGRESS/ PENDING)"
(COMPLETED/ IN-PROGRESS/ PENDING, etc.)

2024-06-23 15:03 UTC, asafMasa approved these changes

2024-07-03 21:40 UTC, shimoncohen requested changes

2024-07-03 21:40 UTC, shimoncohen commented on src/semanticConventions/infra.json
> +            "description": "Status of job/task as stored on db (COMPLETED/ IN-PROGRESS/ PENDING, etc.)"
```suggestion
            "description": "Status of job/task as stored on db (COMPLETED, IN-PROGRESS, PENDING, etc.)"
```

2024-07-03 21:40 UTC, shimoncohen commented on src/semanticConventions/infra.json
> +            "description": "Type of job as stored on db (uuid)"
This is not a type but an ID. Please change description accordingly.
This comment is relevant for `taskId`, `jobType`, and `taskType`'s desriptions as well.

2024-07-03 21:40 UTC, shimoncohen commented on src/semanticConventions/infra.json
> +            "description": "Array of tasks (uuid array)"
```suggestion
            "description": "Array of task ids (uuid array)"
```

2024-07-04 10:01 UTC, CptSchnitz commented on src/semanticConventions/infra.json
> +            "description": "Type of job as stored on db (uuid)"
descriptions*

2024-07-04 10:02 UTC, CptSchnitz commented on src/semanticConventions/infra.json
> +          "status": {
even if its like this in the DB, it might be confusing with other statuses across mapcolonies

2024-07-04 10:02 UTC, CptSchnitz approved these changes

2024-07-29 07:37 UTC, closed without merging