docs : How to deploy Grafana manual
MapColonies/telemetry pull request #71
Opened 2024-07-16 10:47 UTC by RonitKissis

Added a manual to enable easy deployment of the grafana stack locally for easier development and testing.

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2024-07-16 12:14 UTC, CptSchnitz requested changes

2024-07-16 12:14 UTC, CptSchnitz commented on README.md
> +### [Manual for easy local grafana deployment](./localManual.md)
I would put it in a ## title and not under `Motive`.

2024-07-16 12:14 UTC, CptSchnitz commented on localManual.md
> +          - '172.17.0.1:8081'
```suggestion
          - '172.17.0.1:8080'
```

2024-07-16 12:14 UTC, CptSchnitz commented on localManual.md
> +    - The port your service is running on: `8081`
```suggestion
    - The port your service is running on: `8080`
```

2024-07-17 07:09 UTC, CptSchnitz approved these changes

2024-07-17 07:16 UTC, netanelC requested changes
Put the file under docs and rename the file to "local-manual"

2024-07-17 07:38 UTC, netanelC approved these changes

2024-07-17 09:58 UTC, merged