ci: updated flows
MapColonies/telemetry pull request #86
Opened 2024-12-24 09:46 UTC by CptSchnitz

2024-12-24 21:02 UTC, netanelC approved these changes
Good call with the action

2024-12-24 21:03 UTC, netanelC requested changes
Approved by mistake

2024-12-25 12:42 UTC, CptSchnitz commented on .github/workflows/publish.yml
> +          node-version: 20.x
removed

2024-12-25 13:43 UTC, netanelC approved these changes

2024-12-29 07:26 UTC, merged